apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ahhc
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 3.1.0
    helm:
      values: |
        name: ahhc
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: ahhc
        virtualService:
          hosts:
            - "ahhc.org"
            - "www.ahhc.org"
          redirectToPrimary: true
        image:
          repository: zot.soh.re
          name: standouthost/ahhc.org
          tag: "v1.1.1"
          pullPolicy: Always
        secret:
          enabled: true
          name: ahhc-config
        env:
          ADDR: ":8080"

  destination:
    name: k3s.soh.re
    namespace: ahhc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
