apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bible-soh-re
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jmainguy/bible-soh-re.git
    targetRevision: v1.3.2
    path: deploy
  destination:
    name: k3s.soh.re
    namespace: bible-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
