apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmainguy/helm-charts
    targetRevision: main
    path: immich
  destination:
    name: k3s.soh.re
    namespace: immich
  ignoreDifferences:
  - group: postgresql.cnpg.io
    kind: Cluster
    name: immich-postgres
    jsonPointers:
    - /spec/affinity
    - /spec/enablePDB
    - /spec/enableSuperuserAccess
    - /spec/failoverDelay
    - /spec/logLevel
    - /spec/maxSyncReplicas
    - /spec/minSyncReplicas
    - /spec/monitoring
    - /spec/postgresGID
    - /spec/postgresUID
    - /spec/postgresql/parameters
    - /spec/postgresql/syncReplicaElectionConstraint
    - /spec/primaryUpdateMethod
    - /spec/primaryUpdateStrategy
    - /spec/replicationSlots
    - /spec/resources
    - /spec/smartShutdownTimeout
    - /spec/startDelay
    - /spec/stopDelay
    - /spec/switchoverDelay
    jqPathExpressions:
    - .spec.managed.roles[]?.connectionLimit
    - .spec.managed.roles[]?.ensure
    - .spec.managed.roles[]?.inherit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
