apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jmainguy-com
  namespace: argocd
spec:
  project: default
  source:
    chart: jmainguy/helm-webapp
    repoURL: zot.soh.re
    targetRevision: 4.2.2
    helm:
      values: |
        name: jmainguy
        replicaCount: 1
        image:
          repository: zot.soh.re
          name: jmainguy/jmainguy.com
          tag: v1.0.2
          pullPolicy: Always
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: jmainguy

        virtualService: 
          hosts:
            - "jmainguy.com"
            - "www.jmainguy.com"
          redirectToPrimary: true
  destination:
    name: k3s.soh.re
    namespace: jmainguy-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
