apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: jmainguy/helm-webapp
    repoURL: zot.soh.re
    targetRevision: 4.2.3
    helm:
      values: |
        name: nextcloud
        replicaCount: 1
        image:
          name: nextcloud
          repository: docker.io
          tag: 34.0.3
          pullPolicy: "Always"
        service:
          type: ClusterIP
          port: 80
          targetPort: 80
          name: nextcloud
        virtualService: 
          hosts:
            - "nextcloud.soh.re"
        persistence:
          - name: data
            mountPath: /var/www/html
            size: "80Gi"
            accessMode: ReadWriteOnce
        postgres:
          enabled: true
          name: postgres-cluster
          instances: 2
          storage:
            size: 10Gi
          bootstrap:
            initdb:
              database: nextcloud
              owner: nextcloud

  destination:
    name: k3s.soh.re
    namespace: nextcloud-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
