apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ninevoltnine-com
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 3.1.0
    helm:
      values: |
        name: ninevoltnine
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: ninevoltnine
        virtualService:
          hosts:
            - "ninevoltnine.com"
            - "www.ninevoltnine.com"
          redirectToPrimary: true
        image:
          repository: zot.soh.re
          name: ninevoltnine/ninevoltnine.com
          tag: "v1.0.2"
          pullPolicy: Always
        secret:
          enabled: true
          name: ninevoltnine-secrets
        env:
          PORT: "8080"
          NINEVOLT_BASE_URL: "https://ninevoltnine.com"
          NINEVOLT_COMMUNITY_ENABLED: "false"
          NINEVOLT_SECURE_COOKIES: "true"
          NINEVOLT_DOWNLOAD_DIR: "/data/downloads"
        persistence:
          - name: data
            mountPath: /data
            size: 20Gi

  destination:
    name: k3s.soh.re
    namespace: ninevoltnine-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
