apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rightway
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 2.4.0
    helm:
      releaseName: rightway
      values: |
        name: rightway
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: rightway
        virtualService:
          redirectToPrimary: true
          hosts:
            - "rightwaypropertycare.com"
            - "www.rightwaypropertycare.com"
        image:
          repository: zot.standouthost.com/standouthost
          name: rightwaypropertycare.com
          tag: "latest"
          pullPolicy: Always

  destination:
    name: k3s.soh.re
    namespace: rightway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
