apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabotage-harborvane-io
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 3.1.0
    helm:
      values: |
        name: sabotage
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: sabotage
        virtualService:
          hosts:
            - "sabotage.harborvane.io"
        image:
          repository: zot.soh.re
          name: harborvane/sabotage/sabotage
          tag: "latest"
          pullPolicy: Always
        secret:
          enabled: false

  destination:
    name: k3s.soh.re
    namespace: sabotage-harborvane-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
