apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statuscode-soh-re
  namespace: argocd
spec:
  project: default
  source:
    chart: jmainguy/helm-webapp
    repoURL: zot.soh.re
    targetRevision: 4.2.4
    helm:
      values: |
        name: statuscode-soh-re
        image:
          repository: zot.soh.re
          name: jmainguy/statuscode
          tag: v2.0.0
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
          targetPort: 4567
          name: statuscode-soh-re
        virtualService: 
          hosts:
            - "statuscode.soh.re"

  destination:
    name: k3s.soh.re
    namespace: statuscode-soh-re
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
