apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verboseresume-com
  namespace: argocd
spec:
  project: default
  source:
    chart: webapp
    repoURL: zot.soh.re
    targetRevision: 3.1.0
    helm:
      values: |
        name: verboseresume
        replicaCount: 1
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
          name: verboseresume
        virtualService:
          hosts:
            - "verboseresume.com"
            - "www.verboseresume.com"
          redirectToPrimary: true
        image:
          repository: zot.soh.re
          name: verboseresume/verboseresume
          tag: "v1.9.0"
          pullPolicy: Always
        secret:
          enabled: true
          name: verboseresume-secrets
        env:
          PORT: "8080"
          BASE_URL: "https://verboseresume.com"
          UPLOAD_DIR: /data/uploads
          SECURE_COOKIES: "true"
          ADMIN_EMAILS: "jon@soh.re"
        persistence:
          - name: data
            mountPath: /data
            size: 10Gi
        postgres:
          enabled: true
          name: postgres-cluster
          instances: 1
          storage:
            size: 10Gi
          bootstrap:
            initdb:
              database: verboseresume
              owner: verboseresume

  destination:
    name: k3s.soh.re
    namespace: verboseresume-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
