apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  source:
    repoURL: https://github.com/jmainguy/helm-charts
    targetRevision: main
    path: zot
    helm:
      releaseName: zot-ha
      values: |
        notationTrust:
          enabled: true
          storeName: passbolt
          resourceId: 48ae833b-b591-4ca8-92bf-7ec00d07deca
  destination:
    name: k3s.soh.re
    namespace: zot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
